### ISSUE TITLE
UI makes it difficult to post images from phone-sized devices

### ISSUE THREAD

**Issue by eli-oat** [aaronpk/Quill#87]
If you upload an image that makes the image-upload-modal taller than the viewport's height the blue "add" button overflows the screen and is unreachable. 

The modal isn't scrollable, instead you just end up scrolling the screen beneath it as the modal stays put. 

A quick and dirty fix for this would be to constrain the uploaded image's thumbnail's height, but this may lead to confusing some users. Perhaps move the add button to the modal's header, a la iOS modals?

**Comment by aaronpk** [comment]
This has been bugging me too. It appears to be a problem with Bootstrap and Safari. Normally these modals scroll properly, which you can see by editing a tall photo and seeing that the modal is scrollable down to the buttons. On desktop Chrome in responsive mode, the scrolling works fine when adding a new photo as well. It looks like the problem happens when the modal pops up first, then an image is inserted, adjusting the height, and Bootstrap doesn't then recalculate the height of the window to enable that scrolling behavior. I tried updating to a newer 3.x version of Bootstrap, but there were too many other changes that made that into a bigger project. Moving the buttons to the modal header would be too big of a UI change without doing that in every modal and also it would need some visual improvements over the existing buttons for that to work. Instead, I did the quick and dirty fix of setting a max height for the image which should solve this.
