### ISSUE TITLE
Doesn't follow 301 redirects

### ISSUE THREAD

**Issue by shabegom** [aaronpk/Quill#94]
Hello,

First of all, thank you so much for making this! It has been super helpful in getting my own micropub server going. Between Quill and this [youtube video](https://www.youtube.com/watch?v=qka8P26ujP0) I've been able to figure a lot out. Thank you!

I've run into a snag that has stopped me from moving forward. I don't really know PHP, so I'm unclear of the exact issue, but do have a guess.

I am running my micropub server in node using express. nginx is proxying the localhost express address to my public `/micropub` endpoint. The nginx config looks something like this:

```
location '/micropub/' {
    proxy_pass: http://localhost:3000
}
```

When I use Quill to post a note to my micropub endpoint it returns a 301 Permanently moved status code. I believe Quill isn't following the 301 set by nginx.

I did some googling and it appears as if curl in php doesn't follow redirects automatically? And then when it does, it converts the initial POST request into a GET request? https://evertpot.com/curl-redirect-requestbody/

Please let me know if there is any other info I can provide. I can't be much help with a PR since I don't know php, but happy to help in any other capacity.

**Comment by aaronpk** [comment]
Your Micropub endpoint should never be returning HTTP 301, I'm guessing there is something wrong with the nginx config. Maybe you have an http-to-https redirect? Maybe the `proxy_pass` config is wrong?

If the micropub endpoint on your website linked from your GitHub profile is the one in question, it looks like the problem is with the slash. Your website links to `/micropub`, but the nginx config is for `/micropub/`, and nginx is sending a redirect from `https://shbgm.ca/micropub` to `https://shbgm.ca/micropub/`. If you instead include `https://shbgm.ca/micropub/` as your micropub endpoint on your website, Quill should be able to post to it just fine.

In general, it's not a good idea for a POST request to follow 301 redirects, which is why browsers have implemented that by making a GET request to the new location. The Micropub spec itself doesn't say anything about this, but I don't think any Micropub clients will follow a 301 redirect on the micropub endpoint itself. You're better off linking to the actual Micropub endpoint from your site in the first place.
